#!/bin/bash

set -x

random_host()
{
    declare -a instances
    idx=0

    for i in `ls /etc/cassandra-instances.d/*.yaml`; do
	instances[$idx]=`basename $i .yaml`
	idx=$(($idx+1))
    done

    rand_idx=$[ $RANDOM % $idx ]
    echo ${instances[$rand_idx]}
}

read_password()
{
    grep password /etc/cassandra-a/cqlshrc | awk '{ print $3; }'
}


HOST=${HOST:=`random_host`}
OUTPUTDIR=${1:?"Missing argument for SSTable output directory"}


shift 1

# usage: sstableloader [options] <dir_path>
#
# Bulk load the sstables found in the directory <dir_path> to the configured
# cluster.The parent directories of <dir_path> are used as the target
# keyspace/table name. So for instance, to load an sstable named
# Standard1-g-1-Data.db into Keyspace1/Standard1, you will need to have the
# files Standard1-g-1-Data.db and Standard1-g-1-Index.db into a directory
# /path/to/Keyspace1/Standard1/.
#  -alg,--ssl-alg <ALGORITHM>                          Client SSL: algorithm
#                                                      (default: SunX509)
#  -ap,--auth-provider <auth provider>                 custom AuthProvider
#                                                      class name for cassandra authentication
#  -ciphers,--ssl-ciphers <CIPHER-SUITES>              Client SSL:
#                                                      comma-separated list of encryption suites to use
#  -cph,--connections-per-host <connectionsPerHost>    number of concurrent
#                                                      connections-per-host.
#  -d,--nodes <initial hosts>                          Required. try to
#                                                      connect to these hosts (comma separated) initially for ring information
#  -f,--conf-path <path to config file>                cassandra.yaml file
#                                                      path for streaming throughput and client/server SSL.
#  -h,--help                                           display this help
#                                                      message
#  -i,--ignore <NODES>                                 don't stream to this
#                                                      (comma separated) list of nodes
#  -idct,--inter-dc-throttle <inter-dc-throttle>       inter-datacenter
#                                                      throttle speed in Mbits (default unlimited)
#  -ks,--keystore <KEYSTORE>                           Client SSL: full path
#                                                      to keystore
#  -kspw,--keystore-password <KEYSTORE-PASSWORD>       Client SSL: password
#                                                      of the keystore
#     --no-progress                                    don't display
#                                                      progress
#  -p,--port <native transport port>                   port used for native
#                                                      connection (default 9042)
#  -prtcl,--ssl-protocol <PROTOCOL>                    Client SSL:
#                                                      connections protocol to use (default: TLS)
#  -pw,--password <password>                           password for
#                                                      cassandra authentication
#  -sp,--storage-port <storage port>                   port used for
#                                                      internode communication (default 7000)
#  -ssp,--ssl-storage-port <ssl storage port>          port used for TLS
#                                                      internode communication (default 7001)
#  -st,--store-type <STORE-TYPE>                       Client SSL: type of
#                                                      store
#  -t,--throttle <throttle>                            throttle speed in
#                                                      Mbits (default unlimited)
#  -ts,--truststore <TRUSTSTORE>                       Client SSL: full path
#                                                      to truststore
#  -tspw,--truststore-password <TRUSTSTORE-PASSWORD>   Client SSL: password
#                                                      of the truststore
#  -u,--username <username>                            username for
#                                                      cassandra authentication
#  -v,--verbose                                        verbose output
#
# You can provide cassandra.yaml file with -f command line option to set up
# streaming throughput, client and server encryption options. Only
# stream_throughput_outbound_megabits_per_sec, server_encryption_options and
# client_encryption_options are read from yaml. You can override options
# read from cassandra.yaml with corresponding command line options.

sstableloader \
    -f /etc/cassandra-a/cassandra.yaml \
    -u cassandra \
    -pw `read_password` \
    -ts /etc/cassandra-a/tls/server.trust \
    -tspw placeholder \
    -d "$HOST" \
    "$OUTPUTDIR"
