#!/bin/bash

random_host()
{
    declare -a instances
    idx=0

    for i in `ls /etc/cassandra-instances.d/*.yaml`; do
	instances[$idx]=`basename $i .yaml`
	idx=$(($idx+1))
    done

    rand_idx=$[ $RANDOM % $idx ]
    echo ${instances[$rand_idx]}
}

HOST=${HOST:=`random_host`}
JAR=${JAR:=`dirname $0`/krv-cleanup-1.0.0-SNAPSHOT-jar-with-dependencies.jar}
KEYSPACE=${1:?"Missing argument for keyspace name"}
OUTPUTDIR=${OUTPUTDIR:="$PWD"}

shift 1

# Usage: <main class> [options]
#   Options:
#   * --cqlshrc
#       Path to Cassandra cqlshrc file.
#     --dry-run
#       Only log deletions.
#       Default: false
#     --help
#
#     --hostname
#       Cassandra hostname to contact.
#       Default: 127.0.0.1
#   * --keyspace
#       Cassandra keyspace to cleanup.
#     --no-ssl
#       Disable SSL client encryption.
#       Default: false
#   * --output-dir
#       Directory to write output SSTables.
#     --port
#       Cassandra port number.
#       Default: 9042

java \
    -ea \
    -Djavax.net.ssl.trustStore=/etc/cassandra-a/tls/server.trust \
    -jar "$JAR" \
    --cqlshrc /etc/cassandra-a/cqlshrc \
    --hostname "$HOST" \
    --keyspace "$KEYSPACE" \
    --output-dir "$OUTPUTDIR" \
    "$@" 2>&1 | tee "$KEYSPACE"-`date -Iseconds`.log
