#!/bin/bash

random_host()
{
    declare -a instances
    idx=0

    for i in `ls /etc/restbase-instances.d/*.yaml`; do
	instances[$idx]=`basename $i .yaml`
	idx=$(($idx+1))
    done

    rand_idx=$[ $RANDOM % $idx ]
    echo ${instances[$rand_idx]}
}

HOST=${HOST:=`random_host`}
JAR=${JAR:=`dirname $0`/krv-cleanup-1.0.0-SNAPSHOT-jar-with-dependencies.jar}
TRUST_STORE=${TRUST_STORE:=/etc/restbase-a/tls/server.trust}
CQLSHRC=${CQLSHRC:=/etc/restbase-a/cqlshrc}
LOG_LEVEL=${LOG_LEVEL:=ERROR}

# Usage: <main class> [options]
#   Options:
#   * --cqlshrc
#       Path to Cassandra cqlshrc file.
#     --help
#
#     --hostname
#       Cassandra hostname to contact.
#       Default: 127.0.0.1
#     --port
#       Cassandra port number.
#       Default: 9042

LOG_LEVEL="$LOG_LEVEL" java \
         -ea \
         -Djavax.net.ssl.trustStore="$TRUST_STORE" \
         -cp "$JAR" \
         org.wikimedia.restbase.TableLister \
         --cqlshrc "$CQLSHRC" \
         --hostname "$HOST"
